# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laughing Blog
email: goroutine@163.com
description: > # this means to ignore newlines until "baseurl:"
  I am not bad, i just did something stupid --- by one golanger
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "aibomei.github.io" # the base hostname & protocol for your site
twitter_username: aibomei
github_username: aibomei
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

twitter:
  username: aibomei
#instagram_username:

#linkedin_username: lorepirri
#  site:
facebook:
  publisher_id: 1474191545979552
  profile_id: 1474191545979552
  app_id: 126080721296732
  authors: [1474191545979552]

# github on site
github:
  owner_url: https://github.com/aibomei

#weixin
#weixin:
#  username: qutao

#weibo
weibo:
  uid: goroutine

sass:
  sass_dir: assets/_sass
  style: compressed

author:
  name: Tao Qu


images: '/assets/images'
